export const GET_CINEMAS_SUCCESS = 'GET_CINEMAS_SUCCESS';
export const GET_CINEMAS_FAILURE = 'GET_CINEMAS_FAILURE';
export const GET_CINEMA_SUCCESS = 'GET_CINEMA_SUCCESS';
export const GET_CINEMA_FAILURE = 'GET_CINEMA_FAILURE';
export const DELETE_CINEMA_SUCCESS = 'DELETE_CINEMA_SUCCESS';
export const DELETE_CINEMA_FAILURE = 'DELETE_CINEMA_FAILURE';
export const ADD_CINEMA_SUCCESS = 'ADD_CINEMA_SUCCESS';
export const ADD_CINEMA_FAILURE = 'ADD_CINEMA_FAILURE';
export const CLEAR_CINEMA = 'CLEAR_CINEMA';
export const EDIT_CINEMA_FAILURE = 'EDIT_CINEMA_FAILURE';
export const EDIT_CINEMA_SUCCESS = 'EDIT_CINEMA_SUCCESS';
export const SAVE_CINEMA_INFO = 'SAVE_CINEMA_INFO';
export const CLEAR_CINEMA_INFO = 'CLEAR_CINEMA_INFO';
export const ADD_CINEMA_AND_HALLS_SUCCESS = 'ADD_CINEMA_AND_HALLS_SUCCESS';

export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';
export const ADD_MOVIE_FAILURE = 'ADD_MOVIE_FAILURE';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAILURE = 'GET_MOVIE_FAILURE';
export const EDIT_MOVIE_FAILURE = 'EDIT_MOVIE_FAILURE';
export const EDIT_MOVIE_SUCCESS = 'EDIT_MOVIE_SUCCESS';
export const DELETE_MOVIE_FAILURE = 'DELETE_MOVIE_FAILURE';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
export const CLEAR_MOVIE = 'CLEAR_MOVIE';

export const GET_SESSIONS_SUCCESS = 'GET_SESSIONS_SUCCESS';
export const GET_SESSIONS_FAILURE = 'GET_SESSIONS_FAILURE';

export const ADD_HALL_SUCCESS = 'ADD_HALL_SUCCESS';
export const ADD_HALL_FAILURE = 'ADD_HALL_FAILURE';
export const ADD_HALL = 'ADD_HALL';
export const DELETE_NEW_HALL = 'DELETE_NEW_HALL';
export const DELETE_HALL_SUCCESS = 'DELETE_HALL_SUCCESS';
export const DELETE_HALL_FAILURE = 'DELETE_HALL_FAILURE';
export const CLEAR_HALLS = 'CLEAR_HALLS';
export const CLEAR_HALL = 'CLEAR_HALL';
export const GET_HALLS_SUCCESS = 'GET_HALLS_SUCCESS';
export const GET_HALLS_FAILURE = 'GET_HALLS_FAILURE';
export const GET_HALL_SUCCESS = 'GET_HALL_SUCCESS';
export const GET_HALL_FAILURE = 'GET_HALL_FAILURE';
export const EDIT_HALL_FAILURE = 'EDIT_HALL_FAILURE';
export const EDIT_HALL_SUCCESS = 'EDIT_HALL_SUCCESS';

export const ADD_ROW = 'ADD_ROW';
export const ADD_ROWS = 'ADD_ROWS';
export const CLEAR_ROWS = 'CLEAR_ROWS';
